In [1]:
from pytrends.request import TrendReq

#timezone offset in minutes
pytrends = TrendReq(hl = "en-US", tz = 300) #America/New York = 300 minutes

In [10]:
kw_list = ["Tesla"] #search term(s)
pytrends.build_payload(
    kw_list,

    #categories filters
    #0 -  no filter | 784 - Business News |1179 - company news | 1240 - company earnings
    cat = 0,

    #today 12-m, now 7-d, 2004-01-01 2020-01-01
    timeframe = "now 1-d",

    #"" - global | "US" | "CA"
    geo = "",

    # Google property | news | images | froogle | youtube
    gprop = ""
)

In [12]:
df = pytrends.interest_over_time()

C:\Users\sebas\PycharmProjects\CapStone\market-sentiment-analysis\.venv\Lib\site-packages\pytrends\request.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.fillna(False)

In [16]:
df

                     Tesla  isPartial
date
2026-01-21 00:08:00     80      False
2026-01-21 00:16:00     81      False
2026-01-21 00:24:00     79      False
2026-01-21 00:32:00     79      False
2026-01-21 00:40:00     74      False
...                    ...        ...
2026-01-21 23:36:00     87      False
2026-01-21 23:44:00     84      False
2026-01-21 23:52:00     83      False
2026-01-22 00:00:00     84      False
2026-01-22 00:08:00     87       True

[181 rows x 2 columns]

In [15]:
df.loc[df["Tesla"] == 100]

                     Tesla  isPartial
date
2026-01-21 22:32:00    100      False